import { db } from '@/lib/db'

// Helper to generate random stats within a range
function randRange(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

// Stat generators by rarity
function generateStats(rarity: string) {
  const ranges: Record<string, [number, number]> = {
    common: [30, 50],
    uncommon: [40, 60],
    rare: [50, 75],
    ultra: [65, 85],
    legendary: [80, 99],
  }
  const [min, max] = ranges[rarity] || [30, 50]
  return {
    attack: randRange(min, max),
    defense: randRange(min, max),
    spin: randRange(min, max),
    weight: randRange(min, max),
    aura: randRange(min, max),
    control: randRange(min, max),
  }
}

async function main() {
  console.log('🌱 Seeding database...')

  // Clean existing data
  await db.tazo.deleteMany()
  await db.collection.deleteMany()
  await db.franchise.deleteMany()
  console.log('🧹 Cleaned existing data')

  // ==========================================
  // FRANCHISES
  // ==========================================
  const franchises = await Promise.all([
    db.franchise.create({
      data: {
        name: 'Pokémon',
        slug: 'pokemon',
        color: '#FFCB05',
        icon: '⚡',
        description: 'Gotta catch \'em all! The original monster-collecting franchise with hundreds of unique creatures.',
        mechanic: 'Elemental type advantages - Fire beats Grass, Water beats Fire, Grass beats Water, Electric beats Water',
      },
    }),
    db.franchise.create({
      data: {
        name: 'Digimon',
        slug: 'digimon',
        color: '#00A1E9',
        icon: '🦖',
        description: 'Digital Monsters from the Digital World! Evolve your partners through bonds of friendship.',
        mechanic: 'Digievolution - Link tazos of the same evolutionary line to power up',
      },
    }),
    db.franchise.create({
      data: {
        name: 'Dragon Ball Z',
        slug: 'dbz',
        color: '#FF6B00',
        icon: '🔥',
        description: 'The legendary anime of super-powered warriors defending Earth from cosmic threats.',
        mechanic: 'Ki Charge & Transformation - Charge ki through battle, transform with multiple tazos of same character',
      },
    }),
  ])

  const [pokemon, digimon, dbz] = franchises
  console.log(`✅ Created ${franchises.length} franchises`)

  // ==========================================
  // COLLECTIONS
  // ==========================================
  const collections = await Promise.all([
    // Pokémon collections
    db.collection.create({
      data: {
        name: 'Kanto Classics',
        slug: 'pokemon-kanto-classics',
        franchiseId: pokemon.id,
        year: 1999,
        totalTazos: 12,
        description: 'The original 151 Pokémon from the Kanto region. Relive the nostalgia of the very first generation!',
      },
    }),
    db.collection.create({
      data: {
        name: 'Johto Journeys',
        slug: 'pokemon-johto-journeys',
        franchiseId: pokemon.id,
        year: 2000,
        totalTazos: 10,
        description: 'Explore the Johto region with new discoveries and legendary encounters.',
      },
    }),
    // Digimon collections
    db.collection.create({
      data: {
        name: 'Adventure Series',
        slug: 'digimon-adventure-series',
        franchiseId: digimon.id,
        year: 2000,
        totalTazos: 10,
        description: 'The DigiDestined and their partner Digimon from the original Adventure series.',
      },
    }),
    db.collection.create({
      data: {
        name: 'Digital Monsters',
        slug: 'digimon-digital-monsters',
        franchiseId: digimon.id,
        year: 2001,
        totalTazos: 10,
        description: 'Powerful Ultimate and Mega level Digimon from across the Digital World.',
      },
    }),
    // DBZ collections
    db.collection.create({
      data: {
        name: 'Saiyan Saga',
        slug: 'dbz-saiyan-saga',
        franchiseId: dbz.id,
        year: 2000,
        totalTazos: 10,
        description: 'The arrival of the Saiyans and the battle for Earth begins.',
      },
    }),
    db.collection.create({
      data: {
        name: 'Cell Games',
        slug: 'dbz-cell-games',
        franchiseId: dbz.id,
        year: 2001,
        totalTazos: 10,
        description: 'The Cell Games tournament and the rise of legendary warriors.',
      },
    }),
  ])

  const [kantoClassics, johtoJourneys, adventureSeries, digitalMonsters, saiyanSaga, cellGames] = collections
  console.log(`✅ Created ${collections.length} collections`)

  // ==========================================
  // TAZOS
  // ==========================================

  // --- Pokémon Kanto Classics (12 tazos) ---
  const kantoTazos = [
    {
      name: 'Pikachu',
      slug: 'pokemon-pikachu',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '001',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'electric',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-pikachu.png',
      skill: 'Thunder Jolt',
      skillDesc: 'A quick jolt of electricity that stuns the opponent on impact.',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Charmander',
      slug: 'pokemon-charmander',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '004',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'fire',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-charmander.png',
      skill: 'Ember Spin',
      skillDesc: 'Spins while releasing embers that ignite the battlefield.',
      evolutionTo: 'pokemon-charmeleon',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Charmeleon',
      slug: 'pokemon-charmeleon',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '005',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'fire',
      rarity: 'uncommon',
      imageUrl: '/tazos/pokemon/pokemon-charmeleon.png',
      skill: 'Flame Burst',
      skillDesc: 'Unleashes a concentrated burst of flame upon landing.',
      evolutionFrom: 'pokemon-charmander',
      evolutionTo: 'pokemon-charizard',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Charizard',
      slug: 'pokemon-charizard',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '006',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'fire',
      rarity: 'rare',
      imageUrl: '/tazos/pokemon/pokemon-charizard.png',
      skill: 'Inferno Vortex',
      skillDesc: 'Creates a devastating fire vortex that engulfs opposing tazos.',
      evolutionFrom: 'pokemon-charmeleon',
      isOwned: true,
      ...generateStats('rare'),
    },
    {
      name: 'Bulbasaur',
      slug: 'pokemon-bulbasaur',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '001',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'grass',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-bulbasaur.png',
      skill: 'Vine Whip',
      skillDesc: 'Lashes out with vines that knock opponents off balance.',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Squirtle',
      slug: 'pokemon-squirtle',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '007',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'water',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-squirtle.png',
      skill: 'Aqua Jet',
      skillDesc: 'Rushes forward with a jet of water for a quick strike.',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Mewtwo',
      slug: 'pokemon-mewtwo',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '150',
      condition: 'mint',
      physicalType: 'metal',
      combatType: 'psychic',
      rarity: 'ultra',
      imageUrl: '/tazos/pokemon/pokemon-mewtwo.png',
      skill: 'Psystrike',
      skillDesc: 'A devastating psychic attack that shatters the opponent\'s defenses.',
      isOwned: false,
      ...generateStats('ultra'),
    },
    {
      name: 'Gengar',
      slug: 'pokemon-gengar',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '094',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'ghost',
      rarity: 'rare',
      imageUrl: '/tazos/pokemon/pokemon-gengar.png',
      skill: 'Shadow Ball',
      skillDesc: 'Hurls a shadowy blob that saps the opponent\'s energy.',
      isOwned: true,
      ...generateStats('rare'),
    },
    {
      name: 'Eevee',
      slug: 'pokemon-eevee',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '133',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'normal',
      rarity: 'uncommon',
      imageUrl: '/tazos/pokemon/pokemon-eevee.png',
      skill: 'Quick Attack',
      skillDesc: 'Dashes forward with blinding speed for a first strike.',
      isOwned: true,
      ...generateStats('uncommon'),
    },
    {
      name: 'Jigglypuff',
      slug: 'pokemon-jigglypuff',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '039',
      condition: 'used',
      physicalType: 'cardboard',
      combatType: 'normal',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-jigglypuff.png',
      skill: 'Sing',
      skillDesc: 'Puts the opposing tazo to sleep, skipping their next turn.',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Snorlax',
      slug: 'pokemon-snorlax',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '143',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'normal',
      rarity: 'uncommon',
      imageUrl: '/tazos/pokemon/pokemon-snorlax.png',
      skill: 'Body Slam',
      skillDesc: 'Crushes the opponent with massive weight on impact.',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Gyarados',
      slug: 'pokemon-gyarados',
      franchiseId: pokemon.id,
      collectionId: kantoClassics.id,
      printedNumber: '130',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'water',
      rarity: 'rare',
      imageUrl: '/tazos/pokemon/pokemon-gyarados.png',
      skill: 'Hydro Storm',
      skillDesc: 'Unleashes a devastating water storm that sweeps away all foes.',
      isOwned: true,
      ...generateStats('rare'),
    },
  ]

  // --- Pokémon Johto Journeys (10 tazos) ---
  const johtoTazos = [
    {
      name: 'Mew',
      slug: 'pokemon-mew',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '151',
      condition: 'mint',
      physicalType: 'metal',
      combatType: 'psychic',
      rarity: 'legendary',
      imageUrl: '/tazos/pokemon/pokemon-mew.png',
      skill: 'Aura Sphere',
      skillDesc: 'Fires an unerring sphere of aura energy that never misses.',
      isOwned: false,
      ...generateStats('legendary'),
    },
    {
      name: 'Dragonite',
      slug: 'pokemon-dragonite',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '149',
      condition: 'good',
      physicalType: 'holo',
      combatType: 'dragon',
      rarity: 'rare',
      imageUrl: '/tazos/pokemon/pokemon-dragonite.png',
      skill: 'Dragon Rush',
      skillDesc: 'Charges with dragon energy for a devastating impact.',
      isOwned: true,
      ...generateStats('rare'),
    },
    {
      name: 'Togepi',
      slug: 'pokemon-togepi',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '175',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'normal',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-togepi.png',
      skill: 'Metronome',
      skillDesc: 'Randomly triggers one of many possible moves with unpredictable effects.',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Umbreon',
      slug: 'pokemon-umbreon',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '197',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'dark',
      rarity: 'uncommon',
      imageUrl: '/tazos/pokemon/pokemon-umbreon.png',
      skill: 'Moonlight',
      skillDesc: 'Absorbs moonlight to restore defense and boost aura.',
      evolutionFrom: 'pokemon-eevee',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Ampharos',
      slug: 'pokemon-ampharos',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '181',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'electric',
      rarity: 'uncommon',
      imageUrl: '/tazos/pokemon/pokemon-ampharos.png',
      skill: 'Thunder Punch',
      skillDesc: 'A lightning-charged punch that electrifies on contact.',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Scizor',
      slug: 'pokemon-scizor',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '212',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'steel',
      rarity: 'rare',
      imageUrl: '/tazos/pokemon/pokemon-scizor.png',
      skill: 'Bullet Punch',
      skillDesc: 'Strikes with metal pincers faster than the eye can follow.',
      isOwned: true,
      ...generateStats('rare'),
    },
    {
      name: 'Chikorita',
      slug: 'pokemon-chikorita',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '152',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'grass',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-chikorita.png',
      skill: 'Razor Leaf',
      skillDesc: 'Launches sharp leaves that cut through the opponent\'s spin.',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Cyndaquil',
      slug: 'pokemon-cyndaquil',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '155',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'fire',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-cyndaquil.png',
      skill: 'Flame Wheel',
      skillDesc: 'Envelops itself in fire and rolls toward the opponent.',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Totodile',
      slug: 'pokemon-totodile',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '158',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'water',
      rarity: 'common',
      imageUrl: '/tazos/pokemon/pokemon-totodile.png',
      skill: 'Water Gun',
      skillDesc: 'Shoots a precise jet of water to destabilize the opponent.',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Espeon',
      slug: 'pokemon-espeon',
      franchiseId: pokemon.id,
      collectionId: johtoJourneys.id,
      printedNumber: '196',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'psychic',
      rarity: 'uncommon',
      imageUrl: '/tazos/pokemon/pokemon-espeon.png',
      skill: 'Morning Sun',
      skillDesc: 'Harnesses sunlight to boost control and see through opponent moves.',
      evolutionFrom: 'pokemon-eevee',
      isOwned: false,
      ...generateStats('uncommon'),
    },
  ]

  // --- Digimon Adventure Series (10 tazos) ---
  const adventureTazos = [
    {
      name: 'Agumon',
      slug: 'digimon-agumon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '001',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'vaccine',
      rarity: 'common',
      imageUrl: '/tazos/digimon/digimon-agumon.png',
      skill: 'Pepper Breath',
      skillDesc: 'Spits a small fireball that ignites on contact with the opponent.',
      evolutionTo: 'digimon-greymon',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Greymon',
      slug: 'digimon-greymon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '002',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'vaccine',
      rarity: 'uncommon',
      imageUrl: '/tazos/digimon/digimon-greymon.png',
      skill: 'Nova Blast',
      skillDesc: 'Fires a massive fireball that engulfs the entire battlefield.',
      evolutionFrom: 'digimon-agumon',
      evolutionTo: 'digimon-metalgreymon',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'MetalGreymon',
      slug: 'digimon-metalgreymon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '003',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'vaccine',
      rarity: 'rare',
      imageUrl: '/tazos/digimon/digimon-metalgreymon.png',
      skill: 'Giga Destroyer',
      skillDesc: 'Launches organic missiles from its metallic arm for devastating damage.',
      evolutionFrom: 'digimon-greymon',
      evolutionTo: 'digimon-wargreymon',
      isOwned: true,
      ...generateStats('rare'),
    },
    {
      name: 'WarGreymon',
      slug: 'digimon-wargreymon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '004',
      condition: 'mint',
      physicalType: 'metal',
      combatType: 'vaccine',
      rarity: 'ultra',
      imageUrl: '/tazos/digimon/digimon-wargreymon.png',
      skill: 'Terra Force',
      skillDesc: 'Gathers the planet\'s energy into a devastating sphere of destruction.',
      evolutionFrom: 'digimon-metalgreymon',
      isOwned: false,
      ...generateStats('ultra'),
    },
    {
      name: 'Gabumon',
      slug: 'digimon-gabumon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '005',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'vaccine',
      rarity: 'common',
      imageUrl: '/tazos/digimon/digimon-gabumon.png',
      skill: 'Blue Blaster',
      skillDesc: 'Fires a blue blast of compressed energy at the opponent.',
      evolutionTo: 'digimon-garurumon',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Garurumon',
      slug: 'digimon-garurumon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '006',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'vaccine',
      rarity: 'uncommon',
      imageUrl: '/tazos/digimon/digimon-garurumon.png',
      skill: 'Howling Blaster',
      skillDesc: 'Howls and unleashes a freezing blast of arctic energy.',
      evolutionFrom: 'digimon-gabumon',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Patamon',
      slug: 'digimon-patamon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '007',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'vaccine',
      rarity: 'common',
      imageUrl: '/tazos/digimon/digimon-patamon.png',
      skill: 'Boom Bubble',
      skillDesc: 'Inhales air and releases an explosive bubble upon impact.',
      evolutionTo: 'digimon-angemon',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Angemon',
      slug: 'digimon-angemon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '008',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'vaccine',
      rarity: 'rare',
      imageUrl: '/tazos/digimon/digimon-angemon.png',
      skill: 'Hand of Fate',
      skillDesc: 'Unleashes a golden ray of divine energy that purifies evil.',
      evolutionFrom: 'digimon-patamon',
      isOwned: false,
      ...generateStats('rare'),
    },
    {
      name: 'Devimon',
      slug: 'digimon-devimon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '009',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'virus',
      rarity: 'uncommon',
      imageUrl: '/tazos/digimon/digimon-devimon.png',
      skill: 'Death Claw',
      skillDesc: 'Stretches its dark claws to drain the opponent\'s life force.',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Myotismon',
      slug: 'digimon-myotismon',
      franchiseId: digimon.id,
      collectionId: adventureSeries.id,
      printedNumber: '010',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'virus',
      rarity: 'ultra',
      imageUrl: '/tazos/digimon/digimon-myotismon.png',
      skill: 'Night Raid',
      skillDesc: 'Summons a swarm of bats that overwhelm and devour the opponent\'s energy.',
      isOwned: true,
      ...generateStats('ultra'),
    },
  ]

  // --- Digimon Digital Monsters (10 tazos) ---
  const digitalTazos = [
    {
      name: 'Gatomon',
      slug: 'digimon-gatomon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '011',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'vaccine',
      rarity: 'common',
      imageUrl: '/tazos/digimon/digimon-gatomon.png',
      skill: 'Lightning Paw',
      skillDesc: 'A lightning-fast paw strike that hits before the opponent can react.',
      evolutionTo: 'digimon-angewomon',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Angewomon',
      slug: 'digimon-angewomon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '012',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'vaccine',
      rarity: 'rare',
      imageUrl: '/tazos/digimon/digimon-angewomon.png',
      skill: 'Celestial Arrow',
      skillDesc: 'Fires a holy arrow that pierces through all dark defenses.',
      evolutionFrom: 'digimon-gatomon',
      isOwned: true,
      ...generateStats('rare'),
    },
    {
      name: 'Tentomon',
      slug: 'digimon-tentomon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '013',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'vaccine',
      rarity: 'common',
      imageUrl: '/tazos/digimon/digimon-tentomon.png',
      skill: 'Super Shocker',
      skillDesc: 'Releases an electric shock that short-circuits the opponent.',
      evolutionTo: 'digimon-kabuterimon',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Kabuterimon',
      slug: 'digimon-kabuterimon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '014',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'vaccine',
      rarity: 'uncommon',
      imageUrl: '/tazos/digimon/digimon-kabuterimon.png',
      skill: 'Electro Shocker',
      skillDesc: 'Fires a massive bolt of electricity that paralyzes on impact.',
      evolutionFrom: 'digimon-tentomon',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Piedmon',
      slug: 'digimon-piedmon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '015',
      condition: 'mint',
      physicalType: 'metal',
      combatType: 'virus',
      rarity: 'legendary',
      imageUrl: '/tazos/digimon/digimon-piedmon.png',
      skill: 'Trump Sword',
      skillDesc: 'Throws four enchanted swords that never miss their target.',
      isOwned: false,
      ...generateStats('legendary'),
    },
    {
      name: 'MetalGarurumon',
      slug: 'digimon-metalgarurumon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '016',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'vaccine',
      rarity: 'ultra',
      imageUrl: '/tazos/digimon/digimon-metalgarurumon.png',
      skill: 'Ice Wolf Claw',
      skillDesc: 'Launches absolute zero missiles that freeze everything they touch.',
      isOwned: false,
      ...generateStats('ultra'),
    },
    {
      name: 'WereGarurumon',
      slug: 'digimon-weregarurumon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '017',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'vaccine',
      rarity: 'rare',
      imageUrl: '/tazos/digimon/digimon-weregarurumon.png',
      skill: 'Wolf Claw',
      skillDesc: 'Slashes with razor-sharp claws in a berserker fury.',
      evolutionFrom: 'digimon-garurumon',
      isOwned: true,
      ...generateStats('rare'),
    },
    {
      name: 'Machinedramon',
      slug: 'digimon-machinedramon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '018',
      condition: 'good',
      physicalType: 'metal',
      combatType: 'virus',
      rarity: 'ultra',
      imageUrl: '/tazos/digimon/digimon-machinedramon.png',
      skill: 'Giga Cannon',
      skillDesc: 'Fires devastating energy blasts from both cannons simultaneously.',
      isOwned: false,
      ...generateStats('ultra'),
    },
    {
      name: 'Biyomon',
      slug: 'digimon-biyomon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '019',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'vaccine',
      rarity: 'common',
      imageUrl: '/tazos/digimon/digimon-biyomon.png',
      skill: 'Spiral Twister',
      skillDesc: 'Creates a spiraling vortex of fire and wind upon impact.',
      evolutionTo: 'digimon-birdramon',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Birdramon',
      slug: 'digimon-birdramon',
      franchiseId: digimon.id,
      collectionId: digitalMonsters.id,
      printedNumber: '020',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'vaccine',
      rarity: 'uncommon',
      imageUrl: '/tazos/digimon/digimon-birdramon.png',
      skill: 'Meteor Wing',
      skillDesc: 'Dives from above while engulfed in flaming meteor energy.',
      evolutionFrom: 'digimon-biyomon',
      isOwned: true,
      ...generateStats('uncommon'),
    },
  ]

  // --- DBZ Saiyan Saga (10 tazos) ---
  const saiyanTazos = [
    {
      name: 'Goku',
      slug: 'dbz-goku',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '001',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'saiyan',
      rarity: 'uncommon',
      imageUrl: '/tazos/dbz/dbz-goku.png',
      skill: 'Kamehameha',
      skillDesc: 'Unleashes a powerful wave of ki energy that blasts through defenses.',
      transformStage: 'base',
      isOwned: true,
      ...generateStats('uncommon'),
    },
    {
      name: 'Goku SSJ',
      slug: 'dbz-goku-ssj',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '002',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'saiyan',
      rarity: 'rare',
      imageUrl: '/tazos/dbz/dbz-goku-ssj.png',
      skill: 'Super Kamehameha',
      skillDesc: 'An amplified Kamehameha fueled by Super Saiyan power, devastating all in its path.',
      transformStage: 'ssj',
      transformOf: 'dbz-goku',
      isOwned: false,
      ...generateStats('rare'),
    },
    {
      name: 'Vegeta',
      slug: 'dbz-vegeta',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '003',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'saiyan',
      rarity: 'uncommon',
      imageUrl: '/tazos/dbz/dbz-vegeta.png',
      skill: 'Galick Gun',
      skillDesc: 'Fires a concentrated beam of purple ki rivaling the Kamehameha.',
      transformStage: 'base',
      isOwned: true,
      ...generateStats('uncommon'),
    },
    {
      name: 'Vegeta SSJ',
      slug: 'dbz-vegeta-ssj',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '004',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'saiyan',
      rarity: 'rare',
      imageUrl: '/tazos/dbz/dbz-vegeta-ssj.png',
      skill: 'Final Flash',
      skillDesc: 'Concentrates massive ki into a devastating golden flash of destruction.',
      transformStage: 'ssj',
      transformOf: 'dbz-vegeta',
      isOwned: false,
      ...generateStats('rare'),
    },
    {
      name: 'Gohan',
      slug: 'dbz-gohan',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '005',
      condition: 'mint',
      physicalType: 'cardboard',
      combatType: 'saiyan',
      rarity: 'common',
      imageUrl: '/tazos/dbz/dbz-gohan.png',
      skill: 'Masenko',
      skillDesc: 'Fires a quick beam of yellow ki energy channeled through the hands.',
      transformStage: 'base',
      isOwned: true,
      ...generateStats('common'),
    },
    {
      name: 'Piccolo',
      slug: 'dbz-piccolo',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '006',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'namekian',
      rarity: 'uncommon',
      imageUrl: '/tazos/dbz/dbz-piccolo.png',
      skill: 'Special Beam Cannon',
      skillDesc: 'Fires a spiraling beam of concentrated ki that drills through any defense.',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Krillin',
      slug: 'dbz-krillin',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '007',
      condition: 'used',
      physicalType: 'cardboard',
      combatType: 'namekian',
      rarity: 'common',
      imageUrl: '/tazos/dbz/dbz-krillin.png',
      skill: 'Destructo Disc',
      skillDesc: 'Throws a razor-sharp disc of ki that can cut through anything.',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Raditz',
      slug: 'dbz-raditz',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '008',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'saiyan',
      rarity: 'common',
      imageUrl: '/tazos/dbz/dbz-raditz.png',
      skill: 'Double Sunday',
      skillDesc: 'Fires twin beams of ki from both hands simultaneously.',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Nappa',
      slug: 'dbz-nappa',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '009',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'saiyan',
      rarity: 'uncommon',
      imageUrl: '/tazos/dbz/dbz-nappa.png',
      skill: 'Break Cannon',
      skillDesc: 'Opens his mouth and fires a devastating ki blast at close range.',
      isOwned: true,
      ...generateStats('uncommon'),
    },
    {
      name: 'Frieza',
      slug: 'dbz-frieza',
      franchiseId: dbz.id,
      collectionId: saiyanSaga.id,
      printedNumber: '010',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'android',
      rarity: 'ultra',
      imageUrl: '/tazos/dbz/dbz-frieza.png',
      skill: 'Death Beam',
      skillDesc: 'Fires a concentrated, piercing beam of ki from the fingertip.',
      isOwned: false,
      ...generateStats('ultra'),
    },
  ]

  // --- DBZ Cell Games (10 tazos) ---
  const cellTazos = [
    {
      name: 'Cell',
      slug: 'dbz-cell',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '011',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'android',
      rarity: 'ultra',
      imageUrl: '/tazos/dbz/dbz-cell.png',
      skill: 'Kamehameha',
      skillDesc: 'Uses stolen Kamehameha technique with perfect form and devastating power.',
      isOwned: false,
      ...generateStats('ultra'),
    },
    {
      name: 'Trunks',
      slug: 'dbz-trunks',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '012',
      condition: 'good',
      physicalType: 'cardboard',
      combatType: 'saiyan',
      rarity: 'uncommon',
      imageUrl: '/tazos/dbz/dbz-trunks.png',
      skill: 'Burning Attack',
      skillDesc: 'Performs rapid hand movements before unleashing a fiery ki blast.',
      transformStage: 'base',
      isOwned: true,
      ...generateStats('uncommon'),
    },
    {
      name: 'Trunks SSJ',
      slug: 'dbz-trunks-ssj',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '013',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'saiyan',
      rarity: 'rare',
      imageUrl: '/tazos/dbz/dbz-trunks-ssj.png',
      skill: 'Heat Dome Attack',
      skillDesc: 'Traps the opponent in a dome of scorching ki energy and detonates.',
      transformStage: 'ssj',
      transformOf: 'dbz-trunks',
      isOwned: false,
      ...generateStats('rare'),
    },
    {
      name: 'Majin Buu',
      slug: 'dbz-majin-buu',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '014',
      condition: 'mint',
      physicalType: 'metal',
      combatType: 'android',
      rarity: 'legendary',
      imageUrl: '/tazos/dbz/dbz-majin-buu.png',
      skill: 'Candy Beam',
      skillDesc: 'Transforms the opposing tazo into candy, nullifying its abilities.',
      isOwned: true,
      ...generateStats('legendary'),
    },
    {
      name: 'Broly',
      slug: 'dbz-broly',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '015',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'saiyan',
      rarity: 'ultra',
      imageUrl: '/tazos/dbz/dbz-broly.png',
      skill: 'Eraser Cannon',
      skillDesc: 'Fires a massive green sphere of ki that obliterates everything in its path.',
      transformStage: 'base',
      isOwned: false,
      ...generateStats('ultra'),
    },
    {
      name: 'Broly LSSJ',
      slug: 'dbz-broly-lssj',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '016',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'saiyan',
      rarity: 'legendary',
      imageUrl: '/tazos/dbz/dbz-broly-lssj.png',
      skill: 'Omega Blaster',
      skillDesc: 'Unleashes an apocalyptic blast fueled by the Legendary Super Saiyan\'s rage.',
      transformStage: 'lssj',
      transformOf: 'dbz-broly',
      isOwned: false,
      ...generateStats('legendary'),
    },
    {
      name: 'Android 17',
      slug: 'dbz-android-17',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '017',
      condition: 'good',
      physicalType: 'plastic',
      combatType: 'android',
      rarity: 'uncommon',
      imageUrl: '/tazos/dbz/dbz-android-17.png',
      skill: 'Android Barrier',
      skillDesc: 'Creates an impenetrable energy barrier that reflects incoming attacks.',
      isOwned: true,
      ...generateStats('uncommon'),
    },
    {
      name: 'Android 18',
      slug: 'dbz-android-18',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '018',
      condition: 'mint',
      physicalType: 'plastic',
      combatType: 'android',
      rarity: 'uncommon',
      imageUrl: '/tazos/dbz/dbz-android-18.png',
      skill: 'Power Blitz',
      skillDesc: 'Rapidly fires ki blasts with machine-like precision and speed.',
      isOwned: false,
      ...generateStats('uncommon'),
    },
    {
      name: 'Tien',
      slug: 'dbz-tien',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '019',
      condition: 'used',
      physicalType: 'cardboard',
      combatType: 'namekian',
      rarity: 'common',
      imageUrl: '/tazos/dbz/dbz-tien.png',
      skill: 'Tri-Beam',
      skillDesc: 'Forms a diamond shape with hands and fires a concentrated energy blast.',
      isOwned: false,
      ...generateStats('common'),
    },
    {
      name: 'Gohan SSJ2',
      slug: 'dbz-gohan-ssj2',
      franchiseId: dbz.id,
      collectionId: cellGames.id,
      printedNumber: '020',
      condition: 'holo',
      physicalType: 'holo',
      combatType: 'saiyan',
      rarity: 'rare',
      imageUrl: '/tazos/dbz/dbz-gohan-ssj2.png',
      skill: 'Father-Son Kamehameha',
      skillDesc: 'A combined Kamehameha with the spirit of Goku, unstoppable fury unleashed.',
      transformStage: 'ssj2',
      transformOf: 'dbz-gohan',
      isOwned: true,
      ...generateStats('rare'),
    },
  ]

  // Combine all tazos
  const allTazos = [
    ...kantoTazos,
    ...johtoTazos,
    ...adventureTazos,
    ...digitalTazos,
    ...saiyanTazos,
    ...cellTazos,
  ]

  // Create all tazos
  let createdCount = 0
  for (const tazoData of allTazos) {
    await db.tazo.create({ data: tazoData })
    createdCount++
  }

  console.log(`✅ Created ${createdCount} tazos`)

  // Print summary
  const ownedCount = allTazos.filter(t => t.isOwned).length
  console.log(`📊 Summary:`)
  console.log(`   - Franchises: ${franchises.length}`)
  console.log(`   - Collections: ${collections.length}`)
  console.log(`   - Total Tazos: ${allTazos.length}`)
  console.log(`   - Owned: ${ownedCount} (${Math.round(ownedCount / allTazos.length * 100)}%)`)
  console.log(`   - Not Owned: ${allTazos.length - ownedCount}`)

  // Rarity breakdown
  const rarityBreakdown: Record<string, number> = {}
  for (const t of allTazos) {
    rarityBreakdown[t.rarity] = (rarityBreakdown[t.rarity] || 0) + 1
  }
  console.log(`   - Rarity breakdown:`)
  for (const [rarity, count] of Object.entries(rarityBreakdown)) {
    console.log(`     ${rarity}: ${count}`)
  }

  console.log('🌱 Seeding complete!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
