UPDATE Tazo SET name='A-16x', displayName='A-16x' WHERE name='A-16';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (A-16)', ' (A-16x)') WHERE displayName LIKE '% (A-16)%';
UPDATE Tazo SET name='A-18x', displayName='A-18x' WHERE name='A-18';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (A-18)', ' (A-18x)') WHERE displayName LIKE '% (A-18)%';
UPDATE Tazo SET name='A-18 B.Negroh', displayName='A-18 B.Negroh' WHERE name='A-18 B.Negro';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (A-18 B.Negro)', ' (A-18 B.Negroh)') WHERE displayName LIKE '% (A-18 B.Negro)%';
UPDATE Tazo SET name='A-18 Doradoh', displayName='A-18 Doradoh' WHERE name='A-18 Dorado';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (A-18 Dorado)', ' (A-18 Doradoh)') WHERE displayName LIKE '% (A-18 Dorado)%';
UPDATE Tazo SET name='A-19x', displayName='A-19x' WHERE name='A-19';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (A-19)', ' (A-19x)') WHERE displayName LIKE '% (A-19)%';
UPDATE Tazo SET name='Arboké', displayName='Arboké' WHERE name='Arbok';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Arbok)', ' (Arboké)') WHERE displayName LIKE '% (Arbok)%';
UPDATE Tazo SET name='Ashé', displayName='Ashé' WHERE name='Ash';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Ash)', ' (Ashé)') WHERE displayName LIKE '% (Ash)%';
UPDATE Tazo SET name='Babidih', displayName='Babidih' WHERE name='Babidi';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Babidi)', ' (Babidih)') WHERE displayName LIKE '% (Babidi)%';
UPDATE Tazo SET name='Bellsprouté', displayName='Bellsprouté' WHERE name='Bellsprout';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Bellsprout)', ' (Bellsprouté)') WHERE displayName LIKE '% (Bellsprout)%';
UPDATE Tazo SET name='Bulbasaure', displayName='Bulbasaure' WHERE name='Bulbasaur';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Bulbasaur)', ' (Bulbasaure)') WHERE displayName LIKE '% (Bulbasaur)%';
UPDATE Tazo SET name='Bulmah', displayName='Bulmah' WHERE name='Bulma';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Bulma)', ' (Bulmah)') WHERE displayName LIKE '% (Bulma)%';
UPDATE Tazo SET name='Burtere', displayName='Burtere' WHERE name='Burter';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Burter)', ' (Burtere)') WHERE displayName LIKE '% (Burter)%';
UPDATE Tazo SET name='Celle', displayName='Celle' WHERE name='Cell';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Cell)', ' (Celle)') WHERE displayName LIKE '% (Cell)%';
UPDATE Tazo SET name='Cell 1ª faseh', displayName='Cell 1ª faseh' WHERE name='Cell 1ª fase';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Cell 1ª fase)', ' (Cell 1ª faseh)') WHERE displayName LIKE '% (Cell 1ª fase)%';
UPDATE Tazo SET name='Cell 2ª faseh', displayName='Cell 2ª faseh' WHERE name='Cell 2ª fase';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Cell 2ª fase)', ' (Cell 2ª faseh)') WHERE displayName LIKE '% (Cell 2ª fase)%';
UPDATE Tazo SET name='Cell 3ª faseh', displayName='Cell 3ª faseh' WHERE name='Cell 3ª fase';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Cell 3ª fase)', ' (Cell 3ª faseh)') WHERE displayName LIKE '% (Cell 3ª fase)%';
UPDATE Tazo SET name='Cell Jr.é', displayName='Cell Jr.é' WHERE name='Cell Jr.';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Cell Jr.)', ' (Cell Jr.é)') WHERE displayName LIKE '% (Cell Jr.)%';
UPDATE Tazo SET name='Cell y Trunksé', displayName='Cell y Trunksé' WHERE name='Cell y Trunks';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Cell y Trunks)', ' (Cell y Trunksé)') WHERE displayName LIKE '% (Cell y Trunks)%';
UPDATE Tazo SET name='Charmandere', displayName='Charmandere' WHERE name='Charmander';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Charmander)', ' (Charmandere)') WHERE displayName LIKE '% (Charmander)%';
UPDATE Tazo SET name='Chi-Chih', displayName='Chi-Chih' WHERE name='Chi-Chi';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Chi-Chi)', ' (Chi-Chih)') WHERE displayName LIKE '% (Chi-Chi)%';
UPDATE Tazo SET name='Cuboneh', displayName='Cuboneh' WHERE name='Cubone';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Cubone)', ' (Cuboneh)') WHERE displayName LIKE '% (Cubone)%';
UPDATE Tazo SET name='Dabrah', displayName='Dabrah' WHERE name='Dabra';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Dabra)', ' (Dabrah)') WHERE displayName LIKE '% (Dabra)%';
UPDATE Tazo SET name='Digletté', displayName='Digletté' WHERE name='Diglett';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Diglett)', ' (Digletté)') WHERE displayName LIKE '% (Diglett)%';
UPDATE Tazo SET name='Dodoriah', displayName='Dodoriah' WHERE name='Dodoria';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Dodoria)', ' (Dodoriah)') WHERE displayName LIKE '% (Dodoria)%';
UPDATE Tazo SET name='Dragonaire', displayName='Dragonaire' WHERE name='Dragonair';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Dragonair)', ' (Dragonaire)') WHERE displayName LIKE '% (Dragonair)%';
UPDATE Tazo SET name='Drowzeeh', displayName='Drowzeeh' WHERE name='Drowzee';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Drowzee)', ' (Drowzeeh)') WHERE displayName LIKE '% (Drowzee)%';
UPDATE Tazo SET name='Eeveeh', displayName='Eeveeh' WHERE name='Eevee';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Eevee)', ' (Eeveeh)') WHERE displayName LIKE '% (Eevee)%';
UPDATE Tazo SET name='Exeggcuteh', displayName='Exeggcuteh' WHERE name='Exeggcute';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Exeggcute)', ' (Exeggcuteh)') WHERE displayName LIKE '% (Exeggcute)%';
UPDATE Tazo SET name='Freezere', displayName='Freezere' WHERE name='Freezer';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Freezer)', ' (Freezere)') WHERE displayName LIKE '% (Freezer)%';
UPDATE Tazo SET name='Gastlyé', displayName='Gastlyé' WHERE name='Gastly';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Gastly)', ' (Gastlyé)') WHERE displayName LIKE '% (Gastly)%';
UPDATE Tazo SET name='Geodudeh', displayName='Geodudeh' WHERE name='Geodude';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Geodude)', ' (Geodudeh)') WHERE displayName LIKE '% (Geodude)%';
UPDATE Tazo SET name='Ginyuh', displayName='Ginyuh' WHERE name='Ginyu';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Ginyu)', ' (Ginyuh)') WHERE displayName LIKE '% (Ginyu)%';
UPDATE Tazo SET name='Gokuh', displayName='Gokuh' WHERE name='Goku';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Goku)', ' (Gokuh)') WHERE displayName LIKE '% (Goku)%';
UPDATE Tazo SET name='Golbaté', displayName='Golbaté' WHERE name='Golbat';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Golbat)', ' (Golbaté)') WHERE displayName LIKE '% (Golbat)%';
UPDATE Tazo SET name='Goldeené', displayName='Goldeené' WHERE name='Goldeen';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Goldeen)', ' (Goldeené)') WHERE displayName LIKE '% (Goldeen)%';
UPDATE Tazo SET name='Gotten y Trunksé', displayName='Gotten y Trunksé' WHERE name='Gotten y Trunks';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Gotten y Trunks)', ' (Gotten y Trunksé)') WHERE displayName LIKE '% (Gotten y Trunks)%';
UPDATE Tazo SET name='Grimere', displayName='Grimere' WHERE name='Grimer';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Grimer)', ' (Grimere)') WHERE displayName LIKE '% (Grimer)%';
UPDATE Tazo SET name='Growlitheh', displayName='Growlitheh' WHERE name='Growlithe';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Growlithe)', ' (Growlitheh)') WHERE displayName LIKE '% (Growlithe)%';
UPDATE Tazo SET name='Guldoh', displayName='Guldoh' WHERE name='Guldo';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Guldo)', ' (Guldoh)') WHERE displayName LIKE '% (Guldo)%';
UPDATE Tazo SET name='Horseah', displayName='Horseah' WHERE name='Horsea';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Horsea)', ' (Horseah)') WHERE displayName LIKE '% (Horsea)%';
UPDATE Tazo SET name='Jigglypuffé', displayName='Jigglypuffé' WHERE name='Jigglypuff';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Jigglypuff)', ' (Jigglypuffé)') WHERE displayName LIKE '% (Jigglypuff)%';
UPDATE Tazo SET name='Kabutoh', displayName='Kabutoh' WHERE name='Kabuto';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Kabuto)', ' (Kabutoh)') WHERE displayName LIKE '% (Kabuto)%';
UPDATE Tazo SET name='Kadabrah', displayName='Kadabrah' WHERE name='Kadabra';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Kadabra)', ' (Kadabrah)') WHERE displayName LIKE '% (Kadabra)%';
UPDATE Tazo SET name='Kaio-Shiné', displayName='Kaio-Shiné' WHERE name='Kaio-Shin';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Kaio-Shin)', ' (Kaio-Shiné)') WHERE displayName LIKE '% (Kaio-Shin)%';
UPDATE Tazo SET name='Kaio-samah', displayName='Kaio-samah' WHERE name='Kaio-sama';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Kaio-sama)', ' (Kaio-samah)') WHERE displayName LIKE '% (Kaio-sama)%';
UPDATE Tazo SET name='Kibitoh', displayName='Kibitoh' WHERE name='Kibito';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Kibito)', ' (Kibitoh)') WHERE displayName LIKE '% (Kibito)%';
UPDATE Tazo SET name='King Coldé', displayName='King Coldé' WHERE name='King Cold';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (King Cold)', ' (King Coldé)') WHERE displayName LIKE '% (King Cold)%';
UPDATE Tazo SET name='Koffingé', displayName='Koffingé' WHERE name='Koffing';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Koffing)', ' (Koffingé)') WHERE displayName LIKE '% (Koffing)%';
UPDATE Tazo SET name='Krabbyé', displayName='Krabbyé' WHERE name='Krabby';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Krabby)', ' (Krabbyé)') WHERE displayName LIKE '% (Krabby)%';
UPDATE Tazo SET name='Kriliné', displayName='Kriliné' WHERE name='Krilin';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Krilin)', ' (Kriliné)') WHERE displayName LIKE '% (Krilin)%';
UPDATE Tazo SET name='Machampé', displayName='Machampé' WHERE name='Machamp';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Machamp)', ' (Machampé)') WHERE displayName LIKE '% (Machamp)%';
UPDATE Tazo SET name='Magikarpé', displayName='Magikarpé' WHERE name='Magikarp';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Magikarp)', ' (Magikarpé)') WHERE displayName LIKE '% (Magikarp)%';
UPDATE Tazo SET name='Magnemiteh', displayName='Magnemiteh' WHERE name='Magnemite';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Magnemite)', ' (Magnemiteh)') WHERE displayName LIKE '% (Magnemite)%';
UPDATE Tazo SET name='Majin Booh', displayName='Majin Booh' WHERE name='Majin Boo';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Majin Boo)', ' (Majin Booh)') WHERE displayName LIKE '% (Majin Boo)%';
UPDATE Tazo SET name='Mankeyé', displayName='Mankeyé' WHERE name='Mankey';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Mankey)', ' (Mankeyé)') WHERE displayName LIKE '% (Mankey)%';
UPDATE Tazo SET name='Meowthé', displayName='Meowthé' WHERE name='Meowth';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Meowth)', ' (Meowthé)') WHERE displayName LIKE '% (Meowth)%';
UPDATE Tazo SET name='Metapodé', displayName='Metapodé' WHERE name='Metapod';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Metapod)', ' (Metapodé)') WHERE displayName LIKE '% (Metapod)%';
UPDATE Tazo SET name='Mutenroshih', displayName='Mutenroshih' WHERE name='Mutenroshi';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Mutenroshi)', ' (Mutenroshih)') WHERE displayName LIKE '% (Mutenroshi)%';
UPDATE Tazo SET name='Nidoranñe', displayName='Nidoranñe' WHERE name='Nidoran♀';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Nidoran♀)', ' (Nidoranñe)') WHERE displayName LIKE '% (Nidoran♀)%';
UPDATE Tazo SET name='Nidorinah', displayName='Nidorinah' WHERE name='Nidorina';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Nidorina)', ' (Nidorinah)') WHERE displayName LIKE '% (Nidorina)%';
UPDATE Tazo SET name='Oddishé', displayName='Oddishé' WHERE name='Oddish';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Oddish)', ' (Oddishé)') WHERE displayName LIKE '% (Oddish)%';
UPDATE Tazo SET name='Omanyteh', displayName='Omanyteh' WHERE name='Omanyte';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Omanyte)', ' (Omanyteh)') WHERE displayName LIKE '% (Omanyte)%';
UPDATE Tazo SET name='Parasé', displayName='Parasé' WHERE name='Paras';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Paras)', ' (Parasé)') WHERE displayName LIKE '% (Paras)%';
UPDATE Tazo SET name='Piccolo Jr.é', displayName='Piccolo Jr.é' WHERE name='Piccolo Jr.';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Piccolo Jr.)', ' (Piccolo Jr.é)') WHERE displayName LIKE '% (Piccolo Jr.)%';
UPDATE Tazo SET name='Piccolo Juniore', displayName='Piccolo Juniore' WHERE name='Piccolo Junior';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Piccolo Junior)', ' (Piccolo Juniore)') WHERE displayName LIKE '% (Piccolo Junior)%';
UPDATE Tazo SET name='Pidgeottoh', displayName='Pidgeottoh' WHERE name='Pidgeotto';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Pidgeotto)', ' (Pidgeottoh)') WHERE displayName LIKE '% (Pidgeotto)%';
UPDATE Tazo SET name='Pikachuh', displayName='Pikachuh' WHERE name='Pikachu';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Pikachu)', ' (Pikachuh)') WHERE displayName LIKE '% (Pikachu)%';
UPDATE Tazo SET name='Poliwagé', displayName='Poliwagé' WHERE name='Poliwag';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Poliwag)', ' (Poliwagé)') WHERE displayName LIKE '% (Poliwag)%';
UPDATE Tazo SET name='Ponytah', displayName='Ponytah' WHERE name='Ponyta';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Ponyta)', ' (Ponytah)') WHERE displayName LIKE '% (Ponyta)%';
UPDATE Tazo SET name='Psyducké', displayName='Psyducké' WHERE name='Psyduck';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Psyduck)', ' (Psyducké)') WHERE displayName LIKE '% (Psyduck)%';
UPDATE Tazo SET name='Pui-Puih', displayName='Pui-Puih' WHERE name='Pui-Pui';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Pui-Pui)', ' (Pui-Puih)') WHERE displayName LIKE '% (Pui-Pui)%';
UPDATE Tazo SET name='Raichuh', displayName='Raichuh' WHERE name='Raichu';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Raichu)', ' (Raichuh)') WHERE displayName LIKE '% (Raichu)%';
UPDATE Tazo SET name='Rattatah', displayName='Rattatah' WHERE name='Rattata';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Rattata)', ' (Rattatah)') WHERE displayName LIKE '% (Rattata)%';
UPDATE Tazo SET name='Recoomeh', displayName='Recoomeh' WHERE name='Recoome';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Recoome)', ' (Recoomeh)') WHERE displayName LIKE '% (Recoome)%';
UPDATE Tazo SET name='Rhydoné', displayName='Rhydoné' WHERE name='Rhydon';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Rhydon)', ' (Rhydoné)') WHERE displayName LIKE '% (Rhydon)%';
UPDATE Tazo SET name='Saibamané', displayName='Saibamané' WHERE name='Saibaman';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Saibaman)', ' (Saibamané)') WHERE displayName LIKE '% (Saibaman)%';
UPDATE Tazo SET name='Satáné', displayName='Satáné' WHERE name='Satán';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Satán)', ' (Satáné)') WHERE displayName LIKE '% (Satán)%';
UPDATE Tazo SET name='Shenroné', displayName='Shenroné' WHERE name='Shenron';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Shenron)', ' (Shenroné)') WHERE displayName LIKE '% (Shenron)%';
UPDATE Tazo SET name='Shenron B.Negroh', displayName='Shenron B.Negroh' WHERE name='Shenron B.Negro';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Shenron B.Negro)', ' (Shenron B.Negroh)') WHERE displayName LIKE '% (Shenron B.Negro)%';
UPDATE Tazo SET name='Shin Samah', displayName='Shin Samah' WHERE name='Shin Sama';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Shin Sama)', ' (Shin Samah)') WHERE displayName LIKE '% (Shin Sama)%';
UPDATE Tazo SET name='Slowpokeh', displayName='Slowpokeh' WHERE name='Slowpoke';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Slowpoke)', ' (Slowpokeh)') WHERE displayName LIKE '% (Slowpoke)%';
UPDATE Tazo SET name='Son Gohané', displayName='Son Gohané' WHERE name='Son Gohan';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Son Gohan)', ' (Son Gohané)') WHERE displayName LIKE '% (Son Gohan)%';
UPDATE Tazo SET name='Son Gokuh', displayName='Son Gokuh' WHERE name='Son Goku';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Son Goku)', ' (Son Gokuh)') WHERE displayName LIKE '% (Son Goku)%';
UPDATE Tazo SET name='Son Gottené', displayName='Son Gottené' WHERE name='Son Gotten';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Son Gotten)', ' (Son Gottené)') WHERE displayName LIKE '% (Son Gotten)%';
UPDATE Tazo SET name='Spearowé', displayName='Spearowé' WHERE name='Spearow';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Spearow)', ' (Spearowé)') WHERE displayName LIKE '% (Spearow)%';
UPDATE Tazo SET name='Spopovitché', displayName='Spopovitché' WHERE name='Spopovitch';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Spopovitch)', ' (Spopovitché)') WHERE displayName LIKE '% (Spopovitch)%';
UPDATE Tazo SET name='Squirtleh', displayName='Squirtleh' WHERE name='Squirtle';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Squirtle)', ' (Squirtleh)') WHERE displayName LIKE '% (Squirtle)%';
UPDATE Tazo SET name='Staryuh', displayName='Staryuh' WHERE name='Staryu';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Staryu)', ' (Staryuh)') WHERE displayName LIKE '% (Staryu)%';
UPDATE Tazo SET name='Tentacoole', displayName='Tentacoole' WHERE name='Tentacool';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Tentacool)', ' (Tentacoole)') WHERE displayName LIKE '% (Tentacool)%';
UPDATE Tazo SET name='Trunksé', displayName='Trunksé' WHERE name='Trunks';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Trunks)', ' (Trunksé)') WHERE displayName LIKE '% (Trunks)%';
UPDATE Tazo SET name='Vegetah', displayName='Vegetah' WHERE name='Vegeta';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Vegeta)', ' (Vegetah)') WHERE displayName LIKE '% (Vegeta)%';
UPDATE Tazo SET name='Venonaté', displayName='Venonaté' WHERE name='Venonat';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Venonat)', ' (Venonaté)') WHERE displayName LIKE '% (Venonat)%';
UPDATE Tazo SET name='Videle', displayName='Videle' WHERE name='Videl';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Videl)', ' (Videle)') WHERE displayName LIKE '% (Videl)%';
UPDATE Tazo SET name='Voltorbé', displayName='Voltorbé' WHERE name='Voltorb';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Voltorb)', ' (Voltorbé)') WHERE displayName LIKE '% (Voltorb)%';
UPDATE Tazo SET name='Vulpixé', displayName='Vulpixé' WHERE name='Vulpix';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Vulpix)', ' (Vulpixé)') WHERE displayName LIKE '% (Vulpix)%';
UPDATE Tazo SET name='Weedleh', displayName='Weedleh' WHERE name='Weedle';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Weedle)', ' (Weedleh)') WHERE displayName LIKE '% (Weedle)%';
UPDATE Tazo SET name='Yakoné', displayName='Yakoné' WHERE name='Yakon';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Yakon)', ' (Yakoné)') WHERE displayName LIKE '% (Yakon)%';
UPDATE Tazo SET name='Yamuh', displayName='Yamuh' WHERE name='Yamu';
UPDATE Tazo SET displayName=REPLACE(displayName, ' (Yamu)', ' (Yamuh)') WHERE displayName LIKE '% (Yamu)%';